version: '3.8'

services:
  # ============ Backend API ============
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: market-insight-api
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/marketdb
      - REDIS_URL=redis://redis:6379
      - ALPHA_VANTAGE_KEY=${ALPHA_VANTAGE_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - market-insight-network

  # ============ Frontend React App ============
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: market-insight-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - market-insight-network

  # ============ PostgreSQL Database ============
  postgres:
    image: postgres:15-alpine
    container_name: market-insight-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=marketdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - market-insight-network

  # ============ Redis Cache ============
  redis:
    image: redis:7-alpine
    container_name: market-insight-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - market-insight-network

  # ============ Celery Worker for Background Tasks ============
  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: market-insight-celery
    command: celery -A tasks worker --loglevel=info
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/marketdb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - market-insight-network

  # ============ Celery Beat Scheduler ============
  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: market-insight-scheduler
    command: celery -A tasks beat --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - market-insight-network

  # ============ Flower (Celery Monitoring) ============
  flower:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: market-insight-flower
    command: celery -A tasks flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - celery-worker
    restart: unless-stopped
    networks:
      - market-insight-network

  # ============ Nginx Reverse Proxy ============
  nginx:
    image: nginx:alpine
    container_name: market-insight-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - market-insight-network

volumes:
  postgres_data:
  redis_data:

networks:
  market-insight-network:
    driver: bridge
